name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - feat/cdpipeline

env:
  ACR_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: inference-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry using username and password
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_REGISTRY }} \
          --username ${{ secrets.ACR_USERNAME }} \
          --password-stdin

    - name: Set up Docker Buildx (for multi-platform builds if needed)
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      id: docker_build_push
      uses: docker/build-push-action@v5
      with:
        context: . # Build context is the root of the repository
        push: true
        tags: |
          ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} # Tag with commit SHA for uniqueness
        file: Dockerfile # Specify the Dockerfile path relative to context
        # Provide inputs for your script in case of testing
        build-args: |
          INPUT_DATA_PATH=datasets/housing_test.csv
          MODEL_PATH=models/random_forest_model.pkl
          IMPUTER_PATH=models/imputer.pkl
          OUTPUT_PREDICTIONS_PATH=datasets/predictions.csv

    - name: Log image pushed tags
      run: |
        echo "Image ${{ env.IMAGE_NAME }} pushed to ACR with tags: ${{ steps.docker_build_push.outputs.tags }}"
