name: Pull and Run Inference Container

on:
  push:
    branches:
      - feat/cdpipeline

env:
  ACR_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: inference-app
  IMAGE_TAG: latest # Use 'latest' or a specific SHA, e.g., ${{ github.sha }}

jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry using username and password
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_REGISTRY }} \
          --username ${{ secrets.ACR_USERNAME }} \
          --password-stdin

    - name: Pull Docker Image from ACR
      run: |
        docker pull ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Run Inference Container Locally
      run: |
        # Define paths for the container. These paths must match the mounted paths.
        CONTAINER_INPUT_DIR="/app/datasets"
        CONTAINER_MODELS_DIR="/app/models"
        CONTAINER_OUTPUT_DIR="/app/datasets" # Output will be in the same dir as input

        mkdir -p "${{ github.workspace }}/datasets"

        docker run \
          -v "${{ github.workspace }}/datasets:${CONTAINER_INPUT_DIR}" \
          -v "${{ github.workspace }}/models:${CONTAINER_MODELS_DIR}" \
          ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          python scripts/inference.py \
          --input_data_path ${CONTAINER_INPUT_DIR}/housing/housing_test.csv \
          --model_path ${CONTAINER_MODELS_DIR}/random_forest_model.pkl \
          --imputer_path ${CONTAINER_MODELS_DIR}/imputer.pkl \
          --output_predictions_path ${CONTAINER_OUTPUT_DIR}/predictions.csv

    - name: Verify Output
      run: |
        echo "Contents of the datasets directory on the runner:"
        ls -l ${{ github.workspace }}/datasets/
        echo "First few lines of predictions.csv:"
        # Use 'cat' and 'head' to preview, ensure file exists before attempting.
        if [ -f "${{ github.workspace }}/datasets/predictions.csv" ]; then
          cat ${{ github.workspace }}/datasets/predictions.csv | head -n 5
        else
          echo "Error: predictions.csv not found!"
          exit 1
        fi
